name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -G "Unix Makefiles" .
    - name: make
      run: make
    - name: make check
      run: make --check
      
